Tests coverage with Codecov
shirts/microsoft-teams-ruby pull request #5
Opened 2021-07-05 16:20 UTC by pedrofurtado

Hi again, @shirts ! 😄 

I've created the skeleton for setup of Codecov in repo, to provide us the percentage of tests coverage. We can later add some badges in README.md to facilitate the view of this kind of information.

What do you think?

For this PR works well, we just have to do the following: creating an project in Codecov, related to repo, and then get the "secret" generated by codecov and register in Github repo settings as a "Repo secret". When you have time, could you do this for us? Once made this action, the coverage will work for future commits/pull requests 🎉

2021-07-06 22:07 UTC, shirts commented
`CODECOV_TOKEN` secret added

2021-07-07 14:38 UTC, pedrofurtado commented
In next PRs, we can add some badges in README.md to indicate codecov and github CI status. But first we need them merged and running 🥇

2021-07-09 23:34 UTC, pedrofurtado commented
@shirts 🤝 🤓

2021-07-21 20:32 UTC, pedrofurtado commented
@shirts Are we ready for merge? ✅

2021-07-21 23:43 UTC, shirts commented on Gemfile
> +gem "codecov", require: false, group: :test
I'd like to keep all dependencies in the gemspec. This would be a development dependency. Do you have any opinions here?

2021-07-21 23:54 UTC, pedrofurtado commented on Gemfile
> +gem "codecov", require: false, group: :test
Good idea, I will move it to gemspec file 👍

2021-07-21 23:57 UTC, pedrofurtado commented on Gemfile
> +gem "codecov", require: false, group: :test
Moved ✅

2021-07-22 14:10 UTC, shirts requested changes
Squash commits 🙏

2022-08-04 19:47 UTC, closed without merging