Rubocop 🤖
shirts/microsoft-teams-ruby pull request #7
Opened 2021-07-05 19:11 UTC by pedrofurtado

@shirts 

I've disabled some cops, to minimize the changes in source code at this moment.

Later, we can enable one by one, and changing the source code to be rubocop-compliant, in differents PRs 🤝

2021-07-06 21:17 UTC, shirts commented
I'd like to use all-or-none when it comes to RuboCop

```yaml
AllCops:
  NewCops: enable
  SuggestExtensions: false
```

Further updates will be forced to follow the rules.

2021-07-06 21:18 UTC, shirts commented on CHANGELOG.md
> +- Setup of Rubocop
NIT:

```suggestion
- Setup of RuboCop
```

2021-07-06 21:18 UTC, shirts requested changes
I'd like to use all-or-none when it comes to RuboCop

```yaml
AllCops:
  NewCops: enable
  SuggestExtensions: false
```

Further updates will be forced to follow the rules.

2021-07-06 21:43 UTC, pedrofurtado commented
> ```yaml
> AllCops:
>   NewCops: enable
>   SuggestExtensions: false
> ```

The two options `NewCops` and `SuggestExtensions` are already defined in RuboCop file 👍

2021-07-06 22:13 UTC, shirts commented
@pedrofurtado Apologies for the confusion. I had meant to only have those 3 lines in the RuboCop config file. The lack of defined rules will follow the RuboCop defaults, which I think are more than reasonable for now.

2021-07-06 22:18 UTC, pedrofurtado commented
@shirts Don't you prefer to split this changes in 2 PRs? 

The first PR (this one), for just add RuboCop in repo CI without too much file changes. And the second PR (that I can create after this) with the amount of file changes necessary to use all default rules present in Rubocop, which will have much more files for review 👍 

Do you like this approach?

2021-07-09 23:33 UTC, pedrofurtado commented
@shirts 🤝 🤓

2021-07-21 20:32 UTC, pedrofurtado commented
@shirts Is the PR ok? 🤓

2021-07-21 23:37 UTC, shirts commented
@pedrofurtado Like I eluded to above: I'd like to keep the rules scoped to the Ruby community defaults.

2022-08-04 19:47 UTC, closed without merging